/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    XButton: typeof import('@xrepo/ui/dist/es/src/components/button/index.mjs')['XButton']
    XHighlight: typeof import('@xrepo/ui/dist/es/src/components/highlight/index.mjs')['XHighlight']
    XMedia: typeof import('@xrepo/ui/dist/es/src/components/media/index.mjs')['XMedia']
  }
}
